// program where the user has to guess a number generated by a program

function guessNumber(){

    const random = Math.floor(Math.random() * 10) + 1
    const prompt = require("prompt-sync")();

    let num = parseInt(prompt('Enter a number: '));

    while(num !== random){
        num= parseInt(prompt('Guess a number from 1 to 10: '));
    }
    if(num == random){
        console.log('You guessed the correct number.');
    }
}
guessNumber();